config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'search', to:"home#search"
  
  devise_for :recruiters, controllers: { registrations: "recruiters/registrations" }
  devise_for :candidates, controllers: { registrations: "candidate/registrations" }

  resources :companies, only: [:index, :show, :new, :create, :edit, :update] do
    resources :jobs, only: [:show, :new, :create, :edit, :update] do
        post 'apply', on: :member
    end
  end

  resources :candidates, only: [:show, :edit, :update]
  resources :job_applications, only: [:show, :edit, :update] do
    resources :recruiter_feedbacks, only: [:show, :edit, :update] do
      patch 'recruiter_rejected', on: :member
      patch 'recruiter_approved', on: :member
    end
    resources :candidate_feedbacks, only: [:show, :update] do
      patch 'candidate_accepted', on: :member
      patch 'candidate_declined', on: :member
    end
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  has_many :job_applications
  has_many :candidates, through: :job_applications

  enum status: { enabled: 0, disabled: 1}

  def increase_total_application
    self.increment!(:total_application)
    if self.total_jobs == self.total_application
      self.disabled!
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_recruiter!, only: [:new, :create, :edit, :update]
  before_action :authenticate_candidate!, only: [:apply]

  def show
    @job = Job.find(params[:id])
    @company = Company.find(params[:company_id])
  end

  def new
    @company = Company.find(params[:company_id])
    @job = @company.jobs.new
  end

  def create    
    @company = Company.find(params[:company_id])
    @job = @company.jobs.new(job_params)
    if @job.save
      redirect_to company_job_path(@company, @job)
    else  
      render 'new'
    end
  end

  def edit    
    @company = Company.find(params[:company_id])
    @job = Job.find(params[:id])
  end

  def update
    @company = Company.find(params[:company_id])

    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to company_job_path(@company, @job)
    else
      render :edit
    end
  end

  def apply
    job = Job.find(params[:id])
    if JobApplication.find_by(candidate: current_candidate, job: job).nil?
      JobApplication.create!(candidate: current_candidate, job: job)
      flash[:apply_positive] = 'Você candidatou-se para a vaga com sucesso!'
      redirect_to current_candidate
    else
      flash[:apply_negative] = 'Você já candidatou-se para a vaga anteriormente!'
      redirect_to current_candidate
    end
  end

  private

  def job_params
    params.require(:job).permit(
      :title,
      :description,
      :compensation,
      :experience_level,
      :requirements,
      :expiration_date,
      :total_jobs,
      :company_id)
  end
end

app/views/jobs/edit.html.erb
<h3>Editar Vaga</h3>

<%=  form_with model: [@company, @job] do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description, size: "40x5" %>

  <%= f.label :compensation %>
  <%= f.text_field :compensation %>

  <%= f.label :experience_level %>
  <%= f.text_field :experience_level %>

  <%= f.label :requirements %>
  <%= f.text_field :requirements %>

  <%= f.label :expiration_date %>
  <%= f.date_field :expiration_date %>

  <%= f.label :total_jobs %>
  <%= f.text_field :total_jobs %>

  <%= f.submit 'Editar Vaga' %>
<% end %>

app/views/jobs/new.html.erb
<h1>Cadastrar Vaga</h1>

<% if @job.errors.any? %>
  <p>Preencha todos os campos</p>
  <% @job.errors.full_messages.each do |message| %>
    <li> <%= message %> </li>
  <% end %>
<% end %>

<%=  form_with model: [@company, @job] do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description, size: "40x5" %>

  <%= f.label :compensation %>
  <%= f.text_field :compensation %>

  <%= f.label :experience_level %>
  <%= f.text_field :experience_level %>

  <%= f.label :requirements %>
  <%= f.text_field :requirements %>

  <%= f.label :expiration_date %>
  <%= f.date_field :expiration_date %>

  <%= f.label :total_jobs %>
  <%= f.text_field :total_jobs %>

  <%= f.submit 'Cadastrar Vaga' %>
<% end %>

app/views/jobs/show.html.erb
<p> <%= link_to 'Voltar para Vagas', company_path(@company) %> </p>

<h1> <%= @job.title %></h1>

<p> <%= @job.description %> </p>
<p> <%= number_to_currency(@job.compensation, delimiter: ".") %> </p>
<p> <%= @job.experience_level %> </p>
<p> <%= @job.requirements %> </p>
<p> <%= I18n.localize(@job.expiration_date) %> 
    <%= (@job.expiration_date - Date.today).to_i %>
      dias para expirar a vaga
</p>
<p> <%= @job.total_jobs %> </p>

<% if candidate_signed_in? %>
  <p> <%= link_to 'Enviar', apply_company_job_path(@company, @job), method: :post %> </p>
<% end %>

<% if recruiter_signed_in? && current_recruiter.company_id == @company.id%>
  <p> <%= link_to 'Editar vaga', edit_company_job_path(@company, @job) %> </p>
  <br>
  <p> Candidaturas: </p>
  <% @job.job_applications.each do |job_application| %>

    <div style="border: 1px solid lime; width: 50%" >
      <p> <%=  job_application.candidate.full_name  %> </p>
      <p>Status: <%= JobApplication.human_attribute_name("status.#{job_application.status}") %> </p>
      
      <p> <%= link_to 'Detalhes', job_application_path(job_application)%> </p>
    </div>

  <% end %>
<% end %>