config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'search', to:"home#search"
  
  devise_for :recruiters, controllers: { registrations: "recruiters/registrations" }
  devise_for :candidates, controllers: { registrations: "candidate/registrations" }

  resources :companies, only: [:index, :show, :new, :create, :edit, :update] do
    resources :jobs, only: [:show, :new, :create, :edit, :update] do
        post 'apply', on: :member
    end
  end

  resources :candidates, only: [:show, :edit, :update]
  resources :job_applications, only: [:show, :edit, :update] do
    resources :recruiter_feedbacks, only: [:show, :edit, :update] do
      patch 'recruiter_rejected', on: :member
      patch 'recruiter_approved', on: :member
    end
    resources :candidate_feedbacks, only: [:show, :update] do
      patch 'candidate_accepted', on: :member
      patch 'candidate_declined', on: :member
    end
  end
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :candidate
  belongs_to :job
  has_one :recruiter_feedback

  enum status: { pending: 0, recruiter_rejected: 1, recruiter_approved: 2, candidate_accepted: 3, candidate_declined: 4}

  after_create :create_recruiter_feedback

  def recruiter_feedback_rejected
    self.recruiter_rejected!
  end

  def recruiter_feedback_approved
    self.recruiter_approved!
  end
 
  def candidate_feedback_declined
    self.candidate_declined!
  end

  def candidate_feedback_accepted
    self.candidate_accepted!
  end

  def create_recruiter_feedback
    RecruiterFeedback.create!(id: self.id ,job_application: self)
  end 
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  #before_action :authenticate_candidate!
  #before_action :authenticate_recruiter!

  def show
    @job_application = JobApplication.find(params[:id])
    @recruiter_feedback = RecruiterFeedback.find(params[:id])
    @candidate_feedback = CandidateFeedback.find(params[:id])
  end

  def edit
    @job_application = JobApplication.find(params[:id])
  end
  
  def update
    @job_application = JobApplication.find(params[:id])

    if @job_application.update(params.require(:job_application).permit(
      :status,
      :candidate_id,
      :job_id))
      redirect_to @job_application
    else
      render :edit
    end
  end
end

app/views/job_applications/show.html.erb
<h1>Detalhes da candidatura</h1>
  
<% if recruiter_signed_in? %>
  <p> <%= @job_application.job.title %> </p>
  <p> Data expiração: <%= I18n.localize(@job_application.job.expiration_date) %> </p>
  <p> Total de Vagas: <%= @job_application.job.total_jobs %> </p>
  <p> Vagas preenchidas: <%= @job_application.job.total_application %> </p>
  <p> <%= number_to_currency(@job_application.job.compensation,delimiter: '.') %> </p>
  <br>

  <p> <%= @job_application.candidate.full_name %> </p>
  <p> <%= @job_application.candidate.bio %> </p>
  <p> <%= @job_application.candidate.tel %> </p>
  <p> <%= @job_application.candidate.email %> </p>

  <% if @job_application.pending? %>
    <p> <%= link_to 'Rejeitar candidatura', recruiter_rejected_job_application_recruiter_feedback_path(@job_application), method: :patch %> </p>
    <p> <%= link_to 'Aceitar candidatura', recruiter_approved_job_application_recruiter_feedback_path(@job_application), method: :patch %> </p>
  <% end %>
<% end %>

<% if @job_application.candidate_declined? %>
  <p> <%= JobApplication.human_attribute_name("status.#{@job_application.status}") %> </p>
  <p>Motivo: </p>
  <p> <%= @candidate_feedback.declined_msg %> </p>
<% end %>

<% if candidate_signed_in? %>
  <p> <%= @job_application.job.title %> </p>
  <p> <%= @job_application.job.description %> </p>
  <p> <%= number_to_currency(@job_application.job.compensation,delimiter: '.') %> </p>
  <p> <%= @job_application.job.experience_level %> </p>
  <p> <%= @job_application.job.requirements %> </p>
  <p> <%= I18n.localize(@job_application.job.expiration_date) %> </p>
  <br>

  <% if @job_application.recruiter_approved? %>
    <p> <%= link_to 'Rejeitar proposta', candidate_declined_job_application_candidate_feedback_path(@recruiter_feedback), method: :patch %> </p>
    <p> <%= link_to 'Aceitar proposta', candidate_accepted_job_application_candidate_feedback_path(@recruiter_feedback), method: :patch %> </p>
  <% end %>
<% end %>

<% if @job_application.recruiter_rejected? %>
  <p> <%= JobApplication.human_attribute_name("status.#{@job_application.status}") %> </p>
  <p> <%= @recruiter_feedback.rejected_msg %> </p>
<% end %>

<% if @job_application.recruiter_approved? %>
  <p> <%= JobApplication.human_attribute_name("status.#{@job_application.status}") %> </p>
  <p> <%= @recruiter_feedback.approved_msg %> </p>
  <p> <%= number_to_currency(@recruiter_feedback.proposed_compensation, delimiter: ".") %> </p>
  <p> <%= I18n.localize(@recruiter_feedback.date_start) %> </p>  
<% end %>