config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'search', to:"home#search"
  
  devise_for :recruiters, controllers: { registrations: "recruiters/registrations" }
  devise_for :candidates, controllers: { registrations: "candidate/registrations" }

  resources :companies, only: [:index, :show, :new, :create, :edit, :update] do
    resources :jobs, only: [:show, :new, :create, :edit, :update] do
        post 'apply', on: :member
    end
  end

  resources :candidates, only: [:show, :edit, :update]
  resources :job_applications, only: [:show, :edit, :update] do
    resources :recruiter_feedbacks, only: [:show, :edit, :update] do
      patch 'recruiter_rejected', on: :member
      patch 'recruiter_approved', on: :member
    end
    resources :candidate_feedbacks, only: [:show, :update] do
      patch 'candidate_accepted', on: :member
      patch 'candidate_declined', on: :member
    end
  end
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class=" container container-fluid">
    <a class="navbar-brand fw-bold" href="/">Balcão de<br>Empregos</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">    
          <% if recruiter_signed_in? %>
            <p> <%= current_recruiter.email %> </p>
            <p> Empresa:  <%= current_recruiter.company_name %></p>
            <p> <%= link_to 'Painel', company_path(current_recruiter.company_id) %> </p>
            <p> <%= link_to 'Sair', destroy_recruiter_session_path, method: :delete %> </p>
          <% elsif candidate_signed_in? %>
            <p> <%= current_candidate.email %> </p>
            <p> <%= link_to 'Painel', candidate_path(current_candidate) %> </p>
            <p> <%= link_to 'Sair', destroy_candidate_session_path, method: :delete %> </p>
          <% else %>
            <%= link_to 'Recrutador', new_recruiter_session_path, :class => "btn btn-primary me-3" %>
            <%= link_to 'Candidato', new_candidate_session_path, :class => "btn btn-success" %>
          <% end %>
        </li>      
      </ul>
    </div>
  </div>
</nav>