config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'search', to:"home#search"
  
  devise_for :recruiters, controllers: { registrations: "recruiters/registrations" }
  devise_for :candidates, controllers: { registrations: "candidate/registrations" }

  resources :companies, only: [:index, :show, :new, :create, :edit, :update] do
    resources :jobs, only: [:show, :new, :create, :edit, :update] do
        post 'apply', on: :member
    end
  end

  resources :candidates, only: [:show, :edit, :update]
  resources :job_applications, only: [:show, :edit, :update] do
    resources :recruiter_feedbacks, only: [:show, :edit, :update] do
      patch 'recruiter_rejected', on: :member
      patch 'recruiter_approved', on: :member
    end
    resources :candidate_feedbacks, only: [:show, :update] do
      patch 'candidate_accepted', on: :member
      patch 'candidate_declined', on: :member
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :recruiters
  has_many :jobs
  has_one_attached :logo

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_recruiter!, except: [:index, :show]
  before_action :only_recruiter_company, except: [:index, :show]

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @recruiter = current_recruiter
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to @company
    else  
      render 'new'
    end
  end

  def edit
    @company = Company.find(params[:id])
  end
  
  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to @company
    else
      render :edit
    end
  end

  private

  def company_params
    params.require(:company).permit(
      :name,
      :description,
      :address,
      :cnpj,
      :website,
      :linkedin,
      :logo)
  end

  def only_recruiter_company
    company = Company.find(params[:id])

    unless current_recruiter.company_id == company.id
    redirect_to company_path(current_recruiter.company_id)
    end
  end
end

app/views/companies/edit.html.erb
<h1>Cadastrar Empresa</h1>
<% if @company.errors.any? %>
  <p>Preencha todos os campos</p>
  <% @company.errors.full_messages.each do |message| %>
    <li> <%= message %> </li>
  <% end %>
<% end %>

<h3> <%= @company.name %></h3>

<%= form_for @company do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name, value: @company.name, disabled: true %>

  <%= f.label :logo %>
  <%= f.file_field :logo %>

  <%= f.label :description %>
  <%= f.text_area :description, size: "40x5" %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :cnpj %>
  <%= f.text_field :cnpj %>

  <%= f.label :website %>
  <%= f.text_field :website %>

  <%= f.label :linkedin %>
  <%= f.text_field :linkedin %>

  <%= f.submit 'Cadastrar Empresa' %>
<% end %>

app/views/companies/index.html.erb
<% @companies.each do |company| %>
  <h3> <%= link_to company.name, company_path(company.id) %> </h3>

  <% if company.logo.attached? %>
    <%= image_tag company.logo %> 
  <% end %>
  <p> <%= company.description %> </p>
  <p> <%= company.address %> </p>
  <p> <%= company.cnpj %> </p>
  <p> <%= company.website %> </p>
  <p> <%= company.linkedin %> </p>
<% end %>

app/views/companies/new.html.erb
<h1>Cadastrar Empresa</h1>
<% if @company.errors.any? %>
  <p>Preencha todos os campos</p>
  <% @company.errors.full_messages.each do |message| %>
    <li> <%= message %> </li>
  <% end %>
<% end %>

<h3> <%= @recruiter.company_name %></h3>

<%= form_with(model: Company.new) do |f| %>

  <%= f.label :logo %>
  <%= f.file_field :logo %>

  <%= f.label :description %>
  <%= f.text_area :description, size: "40x5" %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :cnpj %>
  <%= f.text_field :cnpj %>

  <%= f.label :website %>
  <%= f.text_field :website %>

  <%= f.label :linkedin %>
  <%= f.text_field :linkedin %>

  <%= f.submit 'Cadastrar Empresa' %>
<% end %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>

<% if recruiter_signed_in? && current_recruiter.admin? %>
  <p> <%= link_to 'Editar empresa', edit_company_path(@company) %> </p>
<% end %>

<% if @company.logo.attached? %>
  <%= image_tag @company.logo %> 
<% end %>
<p> Descrição </p>
<p> <%= @company.description %> </p>
<p> Endereço </p>
<p> <%= @company.address %> </p>
<p> CNPJ </p>
<p> <%= @company.cnpj %> </p>
<p> site </p>
<p> <%= @company.website %> </p>
<p> linkedin </p>
<p> <%= @company.linkedin %> </p>

<% if recruiter_signed_in? && current_recruiter.company_id == @company.id%>
  <p> <%= link_to 'Cadastrar vaga', new_company_job_path(@company) %> </p>
<% end %>
  
<p>Vagas Disponíveis</p>

<div>

  <% @company.jobs.each do |job| %>
    <% if job.total_jobs > job.total_application && Date.today < job.expiration_date %>
      <h3> <%= link_to job.title, company_job_path(@company, job) %> </h3>
      <p> <%= I18n.localize(job.expiration_date) %> </p>
      <p> <%= (job.expiration_date - Date.today).to_i %>  dias para expirar a vaga</p>
      <p> <%= job.experience_level %> </p>
      <p> <%= number_to_currency(job.compensation, delimiter: ".") %> </p>
    <% end %>
  <% end %>

</div>

<%= link_to 'Voltar', companies_path %>